import { Grant } from '../models/grant';

/**
 * 手動で登録する既知の助成金・補助金情報
 * Webスクレイピングだけでは情報を網羅できないため、
 * 調査済みの主要な助成金をここに登録する。
 * 定期的に手動で更新すること。
 */
export function getKnownGrants(): Grant[] {
  const now = new Date().toISOString();

  return [
    // ===== 全国 =====
    {
      id: 'known_musubie_fund',
      name: 'むすびえ・こども食堂基金（年2回募集）',
      organization: '認定NPO法人 全国こども食堂支援センター・むすびえ',
      region: '全国',
      targetProjects: 'こども食堂の運営継続、地域のつながりづくり、シングルファミリー支援活動',
      grantAmount: '上限40万円〜100万円（コースにより異なる）',
      grantPeriod: '1年間',
      applicationDeadline: '春募集: 4月頃 / 秋募集: 10月頃（年度により変動）',
      personnelCosts: '要確認',
      honorarium: '可',
      rent: '可',
      status: '不明',
      url: 'https://musubie.org/news_cat/subsidy/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_kagome_foundation',
      name: 'カゴメみらいやさい財団助成（こども食堂継続応援コース）',
      organization: 'カゴメみらいやさい財団',
      region: '全国',
      targetProjects: '無料もしくは低額で食事を提供する「こども食堂」の活動',
      grantAmount: '1団体上限50万円（継続）/ 10万円（新規開設）',
      grantPeriod: '1年間',
      applicationDeadline: '例年12月〜1月頃',
      personnelCosts: '不可',
      honorarium: '可',
      rent: '可',
      status: '不明',
      url: 'https://kagome-miraiyasai.or.jp/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_familymart_startup',
      name: 'こども食堂スタート応援助成（ファミリーマート＆むすびえ）',
      organization: 'ファミリーマート / むすびえ',
      region: '全国',
      targetProjects: 'これからこども食堂を開設する団体（法人格不問）',
      grantAmount: '1団体上限10万円',
      grantPeriod: '約5ヶ月',
      applicationDeadline: '年2回程度（夏期・冬期）',
      personnelCosts: '不可',
      honorarium: '要確認',
      rent: '要確認',
      status: '不明',
      url: 'https://musubie.org/news_cat/subsidy/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_shinnyo_kodomo',
      name: '真如苑 こども食堂支援助成',
      organization: '真如苑',
      region: '全国',
      targetProjects: '食を通した子どもの支援、居場所づくり、学習支援。年間総事業費200万円以下の団体が対象',
      grantAmount: '上限20万円',
      grantPeriod: '4月1日〜翌年3月31日',
      applicationDeadline: '例年11月〜12月頃',
      personnelCosts: '不可',
      honorarium: '可',
      rent: '不可',
      status: '不明',
      url: 'https://kobo.shinnyo-en.or.jp/kodomo/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_nissei_children',
      name: '日本生命財団 児童・少年の健全育成助成（物品助成）',
      organization: '日本生命財団',
      region: '全国',
      targetProjects: '子育てサークル、子育て支援ネットワーク、児童少年の居場所づくり、子ども食堂、学習支援、障がい児療育支援',
      grantAmount: '1団体上限60万円（物品助成）',
      grantPeriod: '1年間',
      applicationDeadline: '例年6月頃',
      personnelCosts: '不可',
      honorarium: '不可',
      rent: '不可',
      status: '不明',
      url: 'https://www.nihonseimei-zaidan.or.jp/jidou/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_benesse_learning',
      name: 'ベネッセこども基金 経済的困難を抱える子どもの学び支援活動助成',
      organization: '公益財団法人ベネッセこども基金',
      region: '全国',
      targetProjects: '経済的困難を抱える子どもの学習支援、生活支援、居場所提供、外国にルーツを持つ子どもの支援',
      grantAmount: '1団体上限200万円〜400万円',
      grantPeriod: '1年間',
      applicationDeadline: '例年1月頃',
      personnelCosts: '可',
      honorarium: '可',
      rent: '可',
      status: '不明',
      url: 'https://benesse-kodomokikin.or.jp/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_wam_kodomo',
      name: '子供の未来応援基金（WAM助成）',
      organization: '独立行政法人 福祉医療機構（WAM）',
      region: '全国',
      targetProjects: '貧困の状況にある子ども等への草の根支援を行うNPO等への助成。学習支援、居場所提供、食事支援等',
      grantAmount: '上限300万円（少額枠: 30万円または100万円）',
      grantPeriod: '1年間',
      applicationDeadline: '例年10月〜11月頃',
      personnelCosts: '可',
      honorarium: '可',
      rent: '可',
      status: '不明',
      url: 'https://www.wam.go.jp/hp/cat/cat_kodomo.html',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_docomo_npo',
      name: 'ドコモ市民活動団体助成事業',
      organization: 'NPO法人 モバイル・コミュニケーション・ファンド',
      region: '全国',
      targetProjects: '子どもの健全な育成を支援する活動、外国にルーツを持つ子どもの支援',
      grantAmount: '1団体上限100万円',
      grantPeriod: '1年間',
      applicationDeadline: '例年2月〜3月頃',
      personnelCosts: '要確認',
      honorarium: '可',
      rent: '要確認',
      status: '不明',
      url: 'https://www.mcfund.or.jp/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_tetote_children',
      name: 'tetote子ども助成制度',
      organization: 'tetote教育財団',
      region: '全国',
      targetProjects: '子ども食堂運営、子どもの学習支援、子どもの体験活動・実習事業、その他子どもの支援事業',
      grantAmount: '要確認',
      grantPeriod: '1年間',
      applicationDeadline: '例年7月頃',
      personnelCosts: '要確認',
      honorarium: '要確認',
      rent: '要確認',
      status: '不明',
      url: 'https://tetote-edu.or.jp/',
      source: 'known',
      lastUpdated: now,
    },
    {
      id: 'known_akaihane_community',
      name: '赤い羽根共同募金 地域課題解決型助成',
      organization: '中央共同募金会',
      region: '全国',
      targetProjects: '子どもの居場所づくり、学習支援、食事支援、多文化共生支援など地域課題の解決に取り組む活動',
      grantAmount: '上限500万円',
      grantPeriod: '1年間',
      applicationDeadline: '例年1月頃',
      personnelCosts: '可',
      honorarium: '可',
      rent: '可',
      status: '不明',
      url: 'https://www.akaihane.or.jp/',
      source: 'known',
      lastUpdated: now,
    },

    // ===== 愛知県 =====
    {
      id: 'known_aichi_npo_fund',
      name: 'あいちNPO交流プラザ NPO活動助成',
      organization: '愛知県（あいちNPO交流プラザ）',
      region: '愛知県',
      targetProjects: '愛知県内で活動するNPO法人の事業全般。子育て支援、多文化共生等',
      grantAmount: '要確認（年度ごとに変動）',
      grantPeriod: '1年間',
      applicationDeadline: '要確認',
      personnelCosts: '要確認',
      honorarium: '要確認',
      rent: '要確認',
      status: '不明',
      url: 'https://www.aichi-npo.jp/',
      source: 'known',
      lastUpdated: now,
    },

    // ===== 長久手市 =====
    {
      id: 'known_nagakute_npo_setup',
      name: '長久手市 NPO法人設立支援補助金',
      organization: '長久手市',
      region: '長久手市',
      targetProjects: 'NPO法人設立手続きに必要な経費（事務所賃借料、光熱水費、通信運搬費、備品購入費等）',
      grantAmount: '要確認',
      grantPeriod: '当該年度',
      applicationDeadline: '要確認（年度ごとに募集）',
      personnelCosts: '不可',
      honorarium: '不可',
      rent: '可',
      status: '不明',
      url: 'https://www.city.nagakute.lg.jp/machizukuri/shiminkatudo/shimin/NPO/11558.html',
      source: 'known',
      lastUpdated: now,
    },
  ];
}
